fix: dont record various commands
p2sr/SourceAutoRecord pull request #100
Opened 2022-09-16 12:14 UTC by ThisAMJ

When was the last time someone used `sar_hud_inspection`? Is it worth cheat-protecting? Certainly looks quite cheaty

Newly unrecorded commands:
- `sar_fast_load_preset`
- `sar_hud_*`
- `sar_ihud_*`
- `sar_toast_*`
- `sar_sr_hud_*`
- `sar_echo[_nolf]`

Modified help strings for:
- `help`
- `sar_<x>_setpos`
- `sar_hud_order_reset`

LMK if there's anything else that deserves not recording :)

2022-09-17 13:12 UTC, ThisAMJ commented
whoops: when flags are changed from 0/never_as_string on cvars they are given 0-1 range, because that makes sense.

2022-09-18 00:15 UTC, ThisAMJ commented
more precisely, src/Variable.cpp@36
```cpp
// Boolean or String
Variable::Variable(const char *name, const char *value, const char *helpstr, int flags, FnChangeCallback_t callback)
	: Variable() {
	if (flags != 0)
		Create(name, value, flags, helpstr, true, 0, true, 1, callback);
	else
		Create(name, value, flags, helpstr, false, 0, false, 0, callback);
}
```

2022-10-30 03:45 UTC, mlugg requested changes

2022-10-30 03:45 UTC, mlugg commented on src/Variable.cpp
> +	if (flags & ~FCVAR_DONTRECORD != 0)
Precedence bug! This groups as `flags & (~FCVAR_DONTRECORD != 0)`. Change to `if ((flags & ~FCVAR_DONTRECORD) != 0)`

2022-11-12 07:46 UTC, merged